apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cart"
  namespace: ms
  labels:
    app: "cart"
spec:
  selector:
    matchLabels:
      app: "cart"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "cart"
    spec:
      containers:
      - name: "cart"
        image:  comdevops/ui:v2
        ports:
        - containerPort:  1004
          name: "cart"
      imagePullSecrets:
      - name: javapipe
---
apiVersion: v1
kind: Service
metadata:
  name: "cart"
  namespace: ms
spec:
  selector:
    app: "cart"
  type: ClusterIP
  ports:
  - name: "cart"
    port: 1004
    targetPort: 1004
