apiVersion: apps/v1
kind: Deployment
metadata:
  name: "shoe"
  namespace: ms
  labels:
    app: "shoe"
spec:
  selector:
    matchLabels:
      app: "shoe"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "shoe"
    spec:
      containers:
      - name: "shoe"
        image:  comdevops/spring:v2
        ports:
        - containerPort:  1002
          name: "shoe"
      imagePullSecrets:
      - name: javapipe
---
apiVersion: v1
kind: Service
metadata:
  name: "shoe"
  namespace: ms
spec:
  selector:
    app: "shoe"
  type: ClusterIP
  ports:
  - name: "shoe"
    port: 1002
    targetPort: 1002
